language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - xbuild SD.Framework.sln
  - nunit-console ./Test/SD.Framework.Data.Test/bin/Debug/SD.Framework.Data.Test.dll -exclude Integration,NotWorkingOnMono